[package]
name = "cs128h-final-project"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo = "0.11.0"
js-sys = "0.3.83"
ndarray = { version = "0.15" }
ndarray-einsum = "0.8.0"
num-complex = "0.4"
web-sys = { version = "0.3.83", features = [
    "HtmlElement",
    "HtmlInputElement",
    "DragEvent",
    "DataTransfer",
    "Event",
    "Element",
    "Node",
    "Window",
    "Document"
] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
